install.packages('devtools')
library(devtools)
devtools::install_github('lukw34/Rmorfer', force = TRUE)
library('Rmorfer')
analyzeToArray(getFileData("./example/data/Harry Potter i Wiezien Azkabanu.txt"))
